/**
 * MakeEazy Tax Optimization Report — PDF Generator
 * Generates a branded 5-page PDF using jsPDF.
 * Returns base64 string for storage/download.
 */

/* global jspdf */

function generateReportPDF(taxResult, insightResult, inputs, pan) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const W = 210, H = 297;
    const M = 18; // margin
    const CW = W - M * 2; // content width
    const NAVY = [50, 80, 159];
    const ORANGE = [247, 127, 0];
    const GREEN = [22, 163, 74];
    const RED = [220, 38, 38];
    const AMBER = [217, 119, 6];
    const GRAY = [100, 116, 139];
    const DARK = [26, 45, 94];
    const WHITE = [255, 255, 255];
    const LIGHT_BG = [240, 242, 247];

    const fmtNum = n => '₹' + Math.round(n).toLocaleString('en-IN');
    const rec = taxResult.recommendation;
    const bestLabel = rec === 'old' ? 'Old Regime' : rec === 'new' ? 'New Regime' : 'Either Regime';
    let y;

    // ════════════ PAGE 1: COVER ════════════
    // Background
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, W, 85, 'F');

    // Accent bar
    doc.setFillColor(...ORANGE);
    doc.rect(0, 85, W, 4, 'F');

    // Title
    doc.setTextColor(...WHITE);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.text('Tax Optimization', W / 2, 35, { align: 'center' });
    doc.text('Report', W / 2, 48, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('FY 2025-26  ·  AY 2026-27', W / 2, 60, { align: 'center' });

    // User details box
    doc.setFillColor(248, 249, 252);
    doc.roundedRect(M, 100, CW, 50, 4, 4, 'F');
    doc.setDrawColor(200, 210, 230);
    doc.roundedRect(M, 100, CW, 50, 4, 4, 'S');

    doc.setTextColor(...DARK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('TAXPAYER DETAILS', M + 8, 112);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(...GRAY);
    const name = inputs.name || inputs.personalInfo?.name || 'Taxpayer';
    doc.text(`Name: ${name}`, M + 8, 122);
    doc.text(`PAN: ${pan}`, M + 8, 130);
    doc.text(`Income Type: ${inputs.incomeType || inputs._incomeType || 'Salaried'}`, M + 8, 138);
    doc.text(`Assessment Year: 2026-27`, M + 8, 146);

    // Score card
    const score = insightResult.score;
    const band = insightResult.band;
    const scoreColor = score > 80 ? GREEN : score > 60 ? AMBER : RED;

    doc.setFillColor(...scoreColor);
    doc.roundedRect(M, 165, CW, 35, 4, 4, 'F');
    doc.setTextColor(...WHITE);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(`Tax Health Score: ${score}/100`, W / 2, 180, { align: 'center' });
    doc.setFontSize(11);
    doc.text(`Status: ${band}`, W / 2, 190, { align: 'center' });

    // Quick summary
    y = 215;
    doc.setTextColor(...DARK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('Quick Summary', M, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...GRAY);
    const summaryItems = [
        `Old Regime Tax: ${fmtNum(taxResult.old.roundedTax)}`,
        `New Regime Tax: ${fmtNum(taxResult.new.roundedTax)}`,
        `Recommended: ${bestLabel}`,
        `Potential Savings: ${fmtNum(taxResult.absSavings)}`,
        `Insights Found: ${insightResult.counts.total}`,
        `Opportunities: ${insightResult.counts.opportunity}`,
    ];
    for (const item of summaryItems) {
        doc.text('•  ' + item, M + 4, y);
        y += 7;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text('Generated by MakeEazy · makeeazy.in', W / 2, H - 12, { align: 'center' });
    doc.text(`Report Date: ${new Date().toLocaleDateString('en-IN')}`, W / 2, H - 7, { align: 'center' });

    // ════════════ PAGE 2: REGIME COMPARISON ════════════
    doc.addPage();
    y = M;

    // Header bar
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, W, 18, 'F');
    doc.setTextColor(...WHITE);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Regime Comparison — Old vs New', W / 2, 12, { align: 'center' });
    y = 28;

    // Comparison table
    const colL = M;
    const colR = W / 2 + 5;
    const colW = CW / 2 - 5;

    function drawRegimeBox(x, label, result, highlight) {
        doc.setFillColor(highlight ? 240 : 248, highlight ? 248 : 249, highlight ? 255 : 252);
        doc.roundedRect(x, y, colW, 115, 3, 3, 'F');
        if (highlight) {
            doc.setDrawColor(...NAVY);
            doc.setLineWidth(0.8);
            doc.roundedRect(x, y, colW, 115, 3, 3, 'S');
        }

        let ly = y + 10;
        doc.setTextColor(...NAVY);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.text(label, x + colW / 2, ly, { align: 'center' });
        ly += 12;

        doc.setFontSize(22);
        doc.setTextColor(...(highlight ? NAVY : GRAY));
        doc.text(fmtNum(result.roundedTax), x + colW / 2, ly, { align: 'center' });
        ly += 14;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...GRAY);
        const lines = [
            ['Gross Salary', fmtNum(result.grossSalary)],
            ['Std Deduction', fmtNum(result.stdDeduction)],
            ['Net Income', fmtNum(result.normalIncome)],
            ['Deductions', fmtNum(result.totalDeductions)],
            ['Taxable', fmtNum(result.taxableTotal)],
            ['Normal Tax', fmtNum(result.normalTax)],
            ['Rebate 87A', fmtNum(result.rebate)],
            ['Surcharge', fmtNum(result.netSurcharge)],
            ['Cess 4%', fmtNum(result.cess)],
        ];
        for (const [k, v] of lines) {
            doc.text(k, x + 6, ly);
            doc.text(v, x + colW - 6, ly, { align: 'right' });
            ly += 7.5;
        }

        if (highlight) {
            doc.setFillColor(...GREEN);
            doc.roundedRect(x + 8, ly + 2, colW - 16, 8, 2, 2, 'F');
            doc.setTextColor(...WHITE);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(8);
            doc.text('✓ RECOMMENDED', x + colW / 2, ly + 7.5, { align: 'center' });
        }
    }

    drawRegimeBox(colL, 'Old Regime', taxResult.old, rec === 'old');
    drawRegimeBox(colR, 'New Regime', taxResult.new, rec === 'new' || rec === 'same');

    y += 125;

    // Verdict
    doc.setFillColor(rec === 'same' ? 248 : 240, rec === 'same' ? 249 : 253, rec === 'same' ? 252 : 244);
    doc.roundedRect(M, y, CW, 20, 3, 3, 'F');
    doc.setTextColor(...(rec === 'same' ? GRAY : GREEN));
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    const verdictText = rec === 'same'
        ? 'Both regimes result in the same tax liability.'
        : taxResult.regimeLabel;
    doc.text(verdictText, W / 2, y + 12, { align: 'center' });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text('Page 2 of 5  ·  MakeEazy Tax Optimization Report', W / 2, H - 7, { align: 'center' });

    // ════════════ PAGE 3: INSIGHTS ════════════
    doc.addPage();
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, W, 18, 'F');
    doc.setTextColor(...WHITE);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Personalised Tax Insights', W / 2, 12, { align: 'center' });
    y = 28;

    const typeLabels = { risk: '⚠ RISK', opportunity: '💡 OPPORTUNITY', good: '✓ GOOD' };
    const typeColors = { risk: RED, opportunity: AMBER, good: GREEN };
    const typeBg = { risk: [254, 242, 242], opportunity: [255, 251, 235], good: [240, 253, 244] };

    for (const ins of insightResult.insights) {
        if (y > H - 40) { doc.addPage(); y = M; }

        const col = typeColors[ins.type] || GRAY;
        const bg = typeBg[ins.type] || LIGHT_BG;

        doc.setFillColor(...bg);
        const boxH = ins.impact > 0 ? 28 : 22;
        doc.roundedRect(M, y, CW, boxH, 3, 3, 'F');

        // Type badge
        doc.setFillColor(...col);
        doc.roundedRect(M + 4, y + 3, 30, 6, 2, 2, 'F');
        doc.setTextColor(...WHITE);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6);
        doc.text(typeLabels[ins.type] || 'INFO', M + 19, y + 7.5, { align: 'center' });

        // Title
        doc.setTextColor(...DARK);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text(ins.title, M + 38, y + 8);

        // Detail
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...GRAY);
        const detailLines = doc.splitTextToSize(ins.detail, CW - 12);
        doc.text(detailLines[0] || '', M + 4, y + 16);

        // Impact
        if (ins.impact > 0) {
            doc.setTextColor(...col);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9);
            doc.text(`Impact: ${fmtNum(ins.impact)}`, CW + M - 4, y + 8, { align: 'right' });
        }

        y += boxH + 4;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text('Page 3 of 5  ·  MakeEazy Tax Optimization Report', W / 2, H - 7, { align: 'center' });

    // ════════════ PAGE 4: RECOMMENDATIONS ════════════
    doc.addPage();
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, W, 18, 'F');
    doc.setTextColor(...WHITE);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Recommended Actions', W / 2, 12, { align: 'center' });
    y = 28;

    // Sort opportunities by impact descending
    const opportunities = insightResult.insights
        .filter(i => i.type === 'opportunity')
        .sort((a, b) => (b.impact || 0) - (a.impact || 0));

    if (opportunities.length === 0) {
        doc.setTextColor(...GREEN);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text('Your tax profile looks well-optimised!', W / 2, y + 20, { align: 'center' });
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(...GRAY);
        doc.text('No major opportunities identified. Keep up the good work.', W / 2, y + 32, { align: 'center' });
    } else {
        let rank = 1;
        for (const opp of opportunities.slice(0, 5)) {
            doc.setFillColor(248, 249, 252);
            doc.roundedRect(M, y, CW, 30, 3, 3, 'F');

            // Rank circle
            doc.setFillColor(...ORANGE);
            doc.circle(M + 10, y + 12, 6, 'F');
            doc.setTextColor(...WHITE);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(11);
            doc.text(`${rank}`, M + 10, y + 14.5, { align: 'center' });

            // Title + impact
            doc.setTextColor(...DARK);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(11);
            doc.text(opp.title, M + 22, y + 10);

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(...GRAY);
            const detailLines = doc.splitTextToSize(opp.detail, CW - 30);
            doc.text(detailLines[0] || '', M + 22, y + 18);

            if (opp.impact > 0) {
                doc.setTextColor(...GREEN);
                doc.setFont('helvetica', 'bold');
                doc.setFontSize(10);
                doc.text(`Save ${fmtNum(opp.impact)}`, CW + M - 4, y + 10, { align: 'right' });
            }

            y += 34;
            rank++;
        }

        // Total savings
        if (insightResult.totalPotentialSavings > 0) {
            y += 6;
            doc.setFillColor(...GREEN);
            doc.roundedRect(M, y, CW, 18, 3, 3, 'F');
            doc.setTextColor(...WHITE);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(12);
            doc.text(`Total Potential Savings: ${fmtNum(insightResult.totalPotentialSavings)}`, W / 2, y + 12, { align: 'center' });
        }
    }

    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text('Page 4 of 5  ·  MakeEazy Tax Optimization Report', W / 2, H - 7, { align: 'center' });

    // ════════════ PAGE 5: NEXT STEPS ════════════
    doc.addPage();
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, W, 18, 'F');
    doc.setTextColor(...WHITE);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Next Steps', W / 2, 12, { align: 'center' });
    y = 35;

    doc.setTextColor(...DARK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Want Expert Help With Your Filing?', W / 2, y, { align: 'center' });
    y += 14;

    // CTA boxes
    const ctas = [
        { icon: '📅', title: 'Schedule a Tax Strategy Discussion', desc: 'Free 15-min call with our tax experts', link: 'calendly.com/makeeazy/support' },
        { icon: '📱', title: 'Chat With Us on WhatsApp', desc: 'Quick answers to your tax questions', link: 'wa.me/919992819995' },
        { icon: '📋', title: 'Get Your ITR Filed', desc: 'Accurate, compliant filing by CA-backed team', link: 'makeeazy.in' },
    ];

    for (const cta of ctas) {
        doc.setFillColor(248, 249, 252);
        doc.roundedRect(M, y, CW, 28, 3, 3, 'F');
        doc.setDrawColor(200, 210, 230);
        doc.roundedRect(M, y, CW, 28, 3, 3, 'S');

        doc.setFontSize(18);
        doc.text(cta.icon, M + 10, y + 16);

        doc.setTextColor(...NAVY);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.text(cta.title, M + 24, y + 10);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(...GRAY);
        doc.text(cta.desc, M + 24, y + 18);
        doc.text(cta.link, M + 24, y + 24);

        y += 34;
    }

    // Disclaimer
    y += 10;
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    const disclaimer = [
        'Disclaimer: This report is generated based on the information provided by you. It is for informational purposes only',
        'and does not constitute tax advice. Please consult a qualified Chartered Accountant for personalised tax planning.',
        'MakeEazy is not responsible for any decisions made based on this report. Tax laws are subject to change.',
    ];
    for (const line of disclaimer) {
        doc.text(line, W / 2, y, { align: 'center' });
        y += 4;
    }

    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text('Page 5 of 5  ·  MakeEazy Tax Optimization Report', W / 2, H - 7, { align: 'center' });

    // ════════════ RETURN ════════════
    return doc;
}

/**
 * Generate PDF and return as base64 string
 */
function generateReportBase64(taxResult, insightResult, inputs, pan) {
    const doc = generateReportPDF(taxResult, insightResult, inputs, pan);
    return doc.output('datauristring').split(',')[1]; // base64 only
}
